### ISSUE TITLE
Version 0.8.0b7 on pypi vs. documentation

### ISSUE THREAD

**Issue by scovetta** [TwoBitAlchemist/NeoAlchemy#2]
I noticed that only version 0.8.0b7 is available on pypi (`pip install neoalchemy`), but the [README](https://github.com/TwoBitAlchemist/NeoAlchemy/blob/master/README.md) docs show some code samples that need 0.9.0b1. For example `neoalchemy.validators` doesn't exist in tag 0.8.0b7.

Users can just `pip install https://github.com/TwoBitAlchemist/NeoAlchemy/archive/v0.9.0b.tar.gz`, but wondering if there's a reason that 0.9.0b1 isn't on Pypi.

**Comment by TwoBitAlchemist** [comment]
Hi!

This project was done by me as a PoC for something my company did, and ultimately the company diverted its interest and I got quite busy at work. I am currently transitioning jobs and quite busy with that. (As you can see, it took me 4 days to get back to you!)

The code is open source and as always you're free to clone, fork, change, or whatever, anything in the repo. I understand not everyone has the time or skill for that. Although I am very interested in the project, it's not fair to say I have any definite plans to work on it in the foreseeable future. This might change, but for right now it's not under active development.

If you do plan to use or try to extend 0.9, you should know my ideas of how to handle some things changed significantly between 0.8 and 0.9, and one of the reasons it's not released is that the docs are incomplete. There are also some things I still hadn't quite nailed down which is why I haven't got a "1.0" yet.

If there is interest in contributing, feel free to ask me about why I did things or what direction I was planning to take. Even if it takes a while or I have to reread some code or notes to answer you, I'll be happy to try to get back to anyone who reaches out.

Cheers & good luck!
